name: projectwe_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  http: ^0.13.5
  json_serializable: ^6.5.4
  intl: ^0.17.0
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^3.0.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/images/dashboard_images/